### ISSUE TITLE
Reflar - doorman

### ISSUE THREAD

**Issue by Angra974** [rooaaar/lang-french-extended#7]
Bonjour,
il te manque des traductions pour ce fichier de langue.

```
allow-public:
          title: Allow public Sign Up
          switch-label: Make invite code optional when signing up

nav:
      desc: Create invite codes for users to sign up and be assigned to a group

doorman_placeholder_optional: Invite Code (optional)
```

si je peux me permettre, il serait bien je trouve que le fichier de langue garde la même forme/structure que l'original, ce sera plus facile à nous de t'aider dans la recherche des lignes manquantes. 

A partir de traduction via l'original en.yml

```
reflar-doorman:
  forum:
    sign_up:
      invalid_doorkey: Le code d'invitation que vous avez fourni n'est pas valide.
      doorkey_required: Vous devez fournir un code d'invitation.
      doorman_placeholder: Code d'invitation
      doorman_placeholder_optional: Code d'invitation (optionel)

  admin:
    invalid_doorkey: Le code d'invitation que vous avez fourni n'est pas valide.
    doorkey_required: Le code d'invitation que vous avez fourni n'est pas valide.
    nav:
      desc: Créer des codes d'invitation pour que les utilisateurs puissent s'inscrire et être assignés à un groupe
    page:
      title: Doorman
      doorkey:
        used_times: "1 utilisation restante|{remaining} utilisations restantes"
        title: Code d'invitation
        help:
          key: 'Clé: Code que l''utilisateur saisira lors de son inscription.'
          group: 'Groupe: Le groupe auquel l''utilisateur sera ajouté lors de l''inscription.'
          max: 'Utilisations maximum: Le nombre maximum d''utilisations du code, définissez-le sur 0 pour un nombre illimité d''utilisations'
          activates: 'Activation de l''utilisateur: Active automatiquement l''utilisateur lors de son inscription.'
        warning: Ce code d'invitation a déjà été utilisé trop de fois.
        key: Clé
        max_uses: Utilisations maximum
        heading:
          key: Clé
          group: Groupe
          activate: Activation de l'utilisateur
          max_uses: Utilisations maximum
        allow-public:
          title: Autoriser l'inscription publique
          switch-label: Rendre le code d'invitation facultatif lors de l'inscription
```

Cdlt.
